#!/bin/sh
# Writes Config/Secrets.xcconfig from .env, copying ONLY the public keys the app
# needs. Server secrets (JWT_SECRET, TURNSTILE_SECRET_KEY, RESEND_*, PEXELS_API_KEY,
# COLLEGE_SCORECARD_API_KEY) must never reach the app bundle.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${1:-$ROOT/.env}"
OUT="$ROOT/Config/Secrets.xcconfig"

[ -f "$ENV_FILE" ] || { echo "error: $ENV_FILE not found" >&2; exit 1; }

value_of() {
  # Last assignment wins; strips surrounding quotes and whitespace.
  grep -E "^[[:space:]]*$1=" "$ENV_FILE" | tail -n 1 | cut -d= -f2- \
    | sed -E 's/^[[:space:]]*"?//; s/"?[[:space:]]*$//'
}

escape() {
  # xcconfig treats `//` as a comment start.
  printf '%s' "$1" | sed 's#//#/$()/#g'
}

{
  echo "// GENERATED by scripts/gen-secrets.sh — do not edit, do not commit."
  for pair in \
    "SUPABASE_URL:NEXT_PUBLIC_SUPABASE_URL" \
    "SUPABASE_ANON_KEY:NEXT_PUBLIC_SUPABASE_ANON_KEY" \
    "LOGO_DEV_TOKEN:NEXT_PUBLIC_LOGO_DEV_TOKEN" \
    "TURNSTILE_SITE_KEY:NEXT_PUBLIC_TURNSTILE_SITE_KEY"
  do
    key="${pair%%:*}"
    src="${pair#*:}"
    val="$(value_of "$src")"
    [ -n "$val" ] || { echo "error: $src missing in $ENV_FILE" >&2; exit 1; }
    echo "$key = $(escape "$val")"
  done
} > "$OUT"

echo "wrote $OUT"
