// Generates AMSA/DesignSystem/Palette.swift from tailwindcss@4.2.0 theme.css.
// Tailwind v4 defines colors in OKLCH; iPhone Safari renders them in Display P3,
// so we convert OKLCH → P3 (gamut-mapped) to match what the mobile web shows.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { converter, toGamut, parse } from "culori";

const here = dirname(fileURLToPath(import.meta.url));
const theme = readFileSync(resolve(here, "node_modules/tailwindcss/theme.css"), "utf8");
const out = resolve(here, "../AMSA/DesignSystem/Palette.swift");

const FAMILIES = ["gray", "red", "orange", "amber", "yellow", "green", "emerald", "blue", "indigo", "purple", "pink"];
const toP3 = toGamut("p3", "oklch");
const asP3 = converter("p3");

const fmt = (n) => Math.min(1, Math.max(0, n)).toFixed(4);

const lines = [];
for (const family of FAMILIES) {
  const re = new RegExp(`--color-${family}-(\\d+):\\s*(oklch\\([^)]+\\));`, "g");
  const entries = [...theme.matchAll(re)];
  if (entries.length !== 11) throw new Error(`${family}: expected 11 shades, got ${entries.length}`);
  lines.push(`    // ${family}`);
  for (const [, shade, value] of entries) {
    const p3 = asP3(toP3(parse(value)));
    lines.push(
      `    static let ${family}${shade} = Color(.displayP3, red: ${fmt(p3.r)}, green: ${fmt(p3.g)}, blue: ${fmt(p3.b)}) // ${value}`,
    );
  }
}

// Brand colors are sRGB hex in the web source.
const BRAND = [
  ["navy", "#001049", "Primary action buttons, headings"],
  ["navyHover", "#073D97", "hover:bg-[#073D97]"],
  ["navyFocus", "#001A78", "focus:ring-[#001A78], hover:bg-[#001A78]"],
  ["gold", "#FFCA3A", "Avatar background"],
  ["mapBackground", "#F7F9FF", "bg-[#f7f9ff] (research map)"],
];
const hexToSwift = (hex) => {
  const n = parseInt(hex.slice(1), 16);
  const c = (v) => (v / 255).toFixed(4);
  return `Color(.sRGB, red: ${c((n >> 16) & 255)}, green: ${c((n >> 8) & 255)}, blue: ${c(n & 255)})`;
};

const swift = `// GENERATED by tools/gen-palette.mjs from tailwindcss@4.2.0 theme.css — do not edit.
import SwiftUI

enum Palette {
    static let white = Color(.sRGB, red: 1, green: 1, blue: 1)
    static let black = Color(.sRGB, red: 0, green: 0, blue: 0)

    // brand (sRGB hex from the web source)
${BRAND.map(([name, hex, note]) => `    static let ${name} = ${hexToSwift(hex)} // ${hex} — ${note}`).join("\n")}

${lines.join("\n")}
}
`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, swift);
console.log(`wrote ${out}`);
